### ISSUE TITLE
Feat: Change password functionality

### ISSUE THREAD

**Issue by abhi40308** [openMF/digital-bank-ui#4]
#### Feature Request

**Goal**
As a user, I want to be able to change password as done here fims-web-app.

**Comment by giorgiozoppi** [comment]
For SOC2 compliance you may want:
1. send a password reset link by e-mail.
2. upon link click. allow to the user a new password.
3. add an angular validator for bad passwords:
- Maintain an 8-character minimum length requirement
- Allow at least 1 lowercase char, 1 number, 1 special char, 1 uppercase number.

**Comment by abhi40308** [comment]
@giorgiozoppi  I missed these comments while making pr. I have implemented the change password functionality as done in fims-web-app.
For email verification, can we do it with FINCN? I don't know if FINCN Identity has email verification implemented.
I have implemented validators for min length 8 but will include the other checks.

**Comment by giorgiozoppi** [comment]
@abhi40308 no we don't have inside identity i have to provide you an endpoint. Meanwhile keep the validator and we close this. I will open an appropriate endpoint.
