### ISSUE TITLE
Show customer details on row click

### ISSUE THREAD

**Issue by abhi40308** [openMF/digital-bank-ui#40]
#### Feature Request
Currently we have to click the "view" link for customer table. We need to make row clickable for consistency with whole app and more intuitive UI.

**Comment by RadheTians** [comment]
Hi @abhi40308, Can I please work on this?

**Comment by RadheTians** [comment]
@abhi40308 @giorgiozoppi can I proceed with it?

**Comment by abhi40308** [comment]
sure go ahead
