### ISSUE TITLE
Custom styling to change password form 

### ISSUE THREAD

**Issue by RadheTians** [openMF/digital-bank-ui#73]
On the user setting page change password form acquiring almost all remaining space followed by some margin both left and right side, It's not looking cool, it should be **center-aligned** and also there should be a tooltip to both the form-fields.

**OS:** Ubuntu 20.04
**Node:** 14.13.1
**Angular:** CLI: 9.1.7
**Material:** 9.2.4
**Firefox:** 81.0

The idea will look like the below screenshot.

![Screenshot from 2020-12-13 13-27-52](https://user-images.githubusercontent.com/50411704/102006751-851b5500-3d49-11eb-8af4-7df7db954d1a.png)

**Comment by RadheTians** [comment]
@abhi40308 @giorgiozoppi @edcable, should I create PR for this idea?

**Comment by abhi40308** [comment]
@RadheTians Sure go ahead
