### ISSUE TITLE
Bug: Change password form allows with older password 

### ISSUE THREAD

**Issue by RadheTians** [openMF/digital-bank-ui#80]
#### Bug Report

Whenever user tries to change it's password the existing system allows to do so with older password too that doesn't make sense, password should be new only.

**OS:** Ubuntu 20.04
**Node:** 14.13.1
**Angular:** CLI: 9.1.7
**Material:** 9.2.4
**Firefox:** 81.0

#### Steps to reproduce

First time login user directly redirects to change password form **or** Click to the top-right user-icon/username and go to setting.

![Screenshot from 2020-12-16 03-44-23](https://user-images.githubusercontent.com/50411704/102279402-52dc4400-3f51-11eb-9645-f53d43a6ce81.png)

**Comment by RadheTians** [comment]
@abhi40308 @giorgiozoppi should I create PR?

**Comment by giorgiozoppi** [comment]
yes. and refer this in the pr.

**Comment by RadheTians** [comment]
@giorgiozoppi sir, sorry for the delay. I have created a taiko test recorder to validate #81 kindly have a look there.
